//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorsHouseWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Online_Payments
    {
        public int payment_id { get; set; }
        public int trans_id { get; set; }
        public string payment_date { get; set; }
        public string payment_time { get; set; }
        public int ap_id { get; set; }
        public int patient_id { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
